markdown: rdiscount
permalink: /:title/
url: /
name: Web Technology
author: lizhihao
qq: 312084121
email: li_zhihao@sina.com
duoshuo: web
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2067815867
github: lizhihao
pygments: true
safe: true
paginate: 20
about: "攻城狮一头，目前从事Linux的相关运维。	
热爱Linux，开源爱好者，喜欢虚拟化，github等。		
电脑洁癖与性能癖。  	
偶尔微博，偶尔wow。"
