markdown: rdiscount
permalink: /:title/
url: /
name: Web Technology
author: lizhihao
qq: 312084121
email: li_zhihao@sina.com
duoshuo: web
weibo: lizhihao666
github: lizhihao
pygments: true
safe: true
paginate: 30
about: "just a software enginer of web . 
I love it ."
