markdown: rdiscount
permalink: /:title/
url: /
name: Web Technology
author: lizhihao
qq: 312084121
email: li_zhihao@sina.com
duoshuo: web
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: lizhihao666
github: lizhihao
pygments: true
safe: true
paginate: 20
about: "just a software enginer of web . 
I love it ."
